4.6.1018 [sx_sdk_4_6_1000, 461830222c879b324a0234196802522a8d7a2498]

diff --git a/sx_scripts/sxdkernel b/sx_scripts/sxdkernel
--- a/sx_scripts/sxdkernel
+++ b/sx_scripts/sxdkernel
@@ -19,6 +19,7 @@
 # Therefore determine the base, follow a runlevel link name ...
 base=${0##*/}
 link=${base#*[SK][0-9][0-9]}
+usr_params=$*
 # ... and compare them
 if [ $link == $base ] ; then
 	RUNMODE=manual
@@ -38,6 +39,28 @@ if [ -z $FAST_BOOT ]; then
     export FAST_BOOT=0
 fi
 
+if [ -z $SX_I2C_MODE ]; then
+    export SX_I2C_MODE=0
+fi
+
+if [ -z $SX_MST_MODE ]; then
+    export SX_MST_MODE=0
+fi
+
+if [ -z $SX_SKIP_RESET ]; then
+    export SX_SKIP_RESET=0
+fi
+
+# Predefined PCI devices environment variable format:
+# export PREDEFINED_DEV_PCI_BUS=<dev_id>@<bus_id>,<dev_id>@<bus_id> ...
+# EXAMPLE:
+#     export PREDEFINED_DEV_PCI_BUS=1@06:00.0,2@03:00.0
+if [ -z $PREDEFINED_DEV_PCI_BUS ]; then
+	export PREDEFINED_DEV_PCI_BUS_PARAM=""
+else
+	export PREDEFINED_DEV_PCI_BUS_PARAM="predefined_dev_pci_bus=${PREDEFINED_DEV_PCI_BUS}"
+fi
+
 if [ "x$RESUME_SDK" == "x1" ]; then
     FAST_BOOT=1
 fi
@@ -47,27 +70,12 @@ RESTART=0
 UNLOAD_MODULES=""
 STATUS_MODULES="sx_core sx_netdev 8021q"
 
+SXDKERNEL_PRESTART="sxdkernel-pre-start"
+SXDKERNEL_POSTSTOP="sxdkernel-post-stop"
+
 #########################################################################
 # Get a sane screen width
 [ -z "${COLUMNS:-}" ] && COLUMNS=80
-
-[ -z "${CONSOLETYPE:-}" ] && [ -x /sbin/consoletype ] && CONSOLETYPE="`/sbin/consoletype`"
-
-if [ -f /etc/sysconfig/i18n -a -z "${NOLOCALE:-}" ] ; then
-	. /etc/sysconfig/i18n
-	if [ "$CONSOLETYPE" != "pty" ]; then
-		case "${LANG:-}" in
-			ja_JP*|ko_KR*|zh_CN*|zh_TW*)
-				export LC_MESSAGES=en_US
-				;;
-			*)
-				export LANG
-				;;
-		esac
-	else
-		export LANG
-	fi
-fi
 
 echo_success() {
 	echo -n $@
@@ -133,12 +141,24 @@ is_module()
 is_ref()
 {
 	local refcnt
-	refcnt=`cat /sys/module/"$1"/refcnt 2> /dev/nill`
+	refcnt=`cat /sys/module/"$1"/refcnt 2> /dev/null`
 	return $refcnt
 }
 
 start()
 {
+	if [ -x "$SXDKERNEL_PRESTART" ]; then
+		"$SXDKERNEL_PRESTART"
+	else
+		# default sdkernel pre-start procedure
+		lsmod | grep sx_core > /dev/null
+		is_core_running=$?
+		if [ $is_core_running -eq 0 ]; then
+			echo_warning $"sx_core service been already started"
+			return 0
+		fi
+	fi
+
 	/sbin/modprobe 8021q
 	RC=$?
 	if [ $RC -ne 0 ]; then
@@ -147,9 +167,9 @@ start()
 	fi
 
 	if [ -z $CHIP_TYPE ]; then
-		/sbin/modprobe sx_core cq_thread_sched_priority=98 g_chip_type=1 fast_boot=$FAST_BOOT reset_trigger=$RESET_TRIGGER
+		/sbin/modprobe sx_core cq_thread_sched_priority=98 g_chip_type=1 i2c_mode=$SX_I2C_MODE mst_mode=$SX_MST_MODE fast_boot=$FAST_BOOT reset_trigger=$RESET_TRIGGER skip_reset=$SX_SKIP_RESET $PREDEFINED_DEV_PCI_BUS_PARAM
 	else
-		/sbin/modprobe sx_core cq_thread_sched_priority=98 g_chip_type=$CHIP_TYPE fast_boot=$FAST_BOOT reset_trigger=$RESET_TRIGGER
+		/sbin/modprobe sx_core cq_thread_sched_priority=98 g_chip_type=$CHIP_TYPE i2c_mode=$SX_I2C_MODE mst_mode=$SX_MST_MODE fast_boot=$FAST_BOOT reset_trigger=$RESET_TRIGGER skip_reset=$SX_SKIP_RESET $PREDEFINED_DEV_PCI_BUS_PARAM
 	fi
 
 	RC=$?
@@ -158,28 +178,7 @@ start()
 		return $RC
 	fi
 
-	if [ "x$udevd_restart" != "xno" ]; then
-		if [ -x /sbin/udevtrigger ]; then
-			echo "Reloading udev:"
-			/sbin/udevtrigger
-			RC=$?
-			if [ $RC = 1 ]; then
-				echo "Failed to run udevtrigger."
-				return $RC
-			fi
-		fi
-		if [ -x /sbin/udevadm ]; then
-			echo "Reloading udev:"
-			/sbin/udevadm trigger
-			RC=$?
-			if [ $RC = 1 ]; then
-				echo "Failed to run udevadm."
-				return $RC
-			fi
-		fi
-	fi
-
-       /sbin/modprobe sx_netdev
+        /sbin/modprobe sx_netdev
         RC=$?
         if [ $RC -ne 0 ]; then
                 echo_failure $"Loading sx_netdev: "
@@ -195,11 +194,27 @@ start()
 	fi
 
 	major=$(awk -F ' ' '$2 == "sxcdev" { print $1}' /proc/devices)
-	mknod -m 666 /dev/sxdevs/sxcdev c $major 193
+	if [ -z $PREDEFINED_DEV_PCI_BUS ]; then
+		# Single Asic - single char dev - sxcdev
+		mknod -m 666 /dev/sxdevs/sxcdev c $major 1
+	else
+		# Multi Asic - multiple char dev.
+		# for example - if PREDEFINED_DEV_PCI_BUS=1@06:00.0,2@03:00.0
+		# char devices will be sxcdev1 and sxcdev2
+		IFS='@'
+		read -a strarr <<< "${PREDEFINED_DEV_PCI_BUS}"
+		mknod -m 666 /dev/sxdevs/sxcdev${strarr[0]} c $major ${strarr[0]}
+		for (( n=1; n < ${#strarr[*]} - 1; n++ ))
+		do
+			IFS=','
+			read -a dev <<< "${strarr[n]}"
+			mknod -m 666 /dev/sxdevs/sxcdev${dev[1]} c $major ${dev[1]}
+		done
+	fi
 
 	RC=$?
 	if [ $RC -ne 0 ]; then
-		echo_failure $"Preparing /dev/sxdevs/sxcdev device"
+		echo_failure $"Preparing /dev/sxdevs/sxcdev major='$major' device"
 		return $RC
 	fi
 
@@ -215,13 +230,25 @@ start()
 
     RC=$?
     if [ $RC -ne 0 ]; then
-        echo_failure $"Preparing /dev/sxdevs/bfdcdev device"
+        echo_failure $"Preparing /dev/sxdevs/bfdcdev major='$major' device"
         return $RC
     fi
 
-	echo_success $"Loading SX driver: "
+    echo_success $"Loading SX driver: "
 
-	return $RC
+    # check if we have sx_ib driver installed (on IB switch)
+    # if so, we'll load it.
+    /sbin/modinfo sx_ib > /dev/null 2>&1
+    RC=$?
+
+    if [ $RC -eq 0 ]; then
+        /sbin/modprobe sx_ib
+        RC=$?
+    else
+        RC=0
+    fi
+
+    return $RC
 }
 
 rm_mod()
@@ -308,6 +335,14 @@ stop()
 
 	local done=0
 
+    # check if we have sx_ib up (on IB switch)
+    # if so, we'll unload it
+    if is_module sx_ib; then
+        is_ref sx_ib
+        unload sx_ib
+        done=1
+    fi
+
     # Unload sx_bfd
     if is_module sx_bfd; then
         is_ref sx_bfd
@@ -315,31 +350,30 @@ stop()
         done=1
     fi
 
-        # Unload mlx_sx_netdev
-	if is_module sx_netdev; then
-		is_ref sx_netdev
-		unload sx_netdev
-	fi
+	if [ -x "$SXDKERNEL_POSTSTOP" ]; then
+		"$SXDKERNEL_POSTSTOP"
+	else
+		# default sxdkernel post-stop procedure
+		# Unload mlx_sx_netdev
+		if is_module sx_netdev; then
+			is_ref sx_netdev
+			unload sx_netdev
+		fi
 
-	# Unload mlx_sx_core
-	if is_module sx_core; then
-		is_ref sx_core
-		unload sx_core
-		rm -rf /dev/sxdevs
-		done=1
-	fi
+		# Unload mlx_sx_core
+		if is_module sx_core; then
+			is_ref sx_core
+			unload sx_core
+			rm -rf /dev/sxdevs
+			done=1
+		fi
 
-	if is_module 8021q; then
-		is_ref 8021q
-		unload 8021q
-		done=1
+		# don't unload 8021q because some system components might use it
 	fi
-
 
 	if [ $done -eq 1 ]; then
 		echo_success $"Unloading SX driver: "
 	fi
-	sleep 1
 }
 
 status()
@@ -376,7 +410,7 @@ status()
 RC=0
 start_time=$(date +%s | tr -d '[:space:]')
 
-trap_handler()
+default_trap_handler()
 {
 	let run_time=$(date +%s | tr -d '[:space:]')-${start_time}
 
@@ -389,7 +423,77 @@ trap_handler()
 	return 0
 }
 
-trap 'trap_handler' 2 9 15
+SCRIPTNAME=$(basename $0)
+LOCK_DIR="/var/lock/${SCRIPTNAME}"
+PIDFILE="${LOCK_DIR}/PID"
+
+lock()
+{
+  mkdir $LOCK_DIR 2> /dev/null
+  if [ $? == 0 ]; then
+     echo $$ > $PIDFILE
+     DO_UNLOCK=1
+     return 0
+  else
+    return 1
+  fi
+}
+
+remove_lock()
+{
+  rm -rf $LOCK_DIR
+}
+
+exit_on_signal()
+{
+  default_trap_handler
+  echo "Kill, cleanup..."
+  if [ "$DO_UNLOCK" != "0" ]; then
+     remove_lock
+  fi
+  exit 1
+}
+
+exit_on_end()
+{
+  if [ "$DO_UNLOCK" != "0" ]; then
+    remove_lock
+  fi
+  exit $1
+}
+
+lock_failed()
+{
+  # check for PID
+  PID=$(cat $PIDFILE)
+
+  # Maybe there was an error reading the PID file
+  if [ $? != 0 ]; then
+     echo "$PIDFILE read failed, $SCRIPTNAME is running (PID ${PID})" >&2
+     DO_UNLOCK=1
+     exit 1
+  fi
+
+  # Check if the PID is really existing
+  if ! kill -0 $PID &>/dev/null; then
+     echo "Removing stale lock of nonexistant PID ${PID}" >&2
+     remove_lock
+     echo "Restarting myself (${SCRIPTNAME})" >&2
+     # On Unix-like operating systems, exec is a builtin command of the Bash shell. 
+     # It allows you to execute a command that completely replaces the current process. 
+     # The current shell process is destroyed, and entirely replaced by the command you specify.
+     exec "$0" $usr_params
+  else
+     echo "Locking failed, another instance of $SCRIPTNAME is still running (PID ${PID})" >&2
+     DO_UNLOCK=0
+     exit 1
+  fi
+}
+trap exit_on_signal INT KILL TERM 
+trap 'exit_on_end $?' QUIT EXIT
+
+# Lock mechanism to insure sxdkernel run as singleton 
+lock || lock_failed
 
 case $ACTION in
 	start)
