4.4.2414 [sx_sdk_4_4_2400, 61acf19c31a35e5cabf0692951330c61e74d8cc0]

diff --git a/sx_scripts/sxdkernel b/sx_scripts/sxdkernel
--- a/sx_scripts/sxdkernel
+++ b/sx_scripts/sxdkernel
@@ -19,6 +19,7 @@
 # Therefore determine the base, follow a runlevel link name ...
 base=${0##*/}
 link=${base#*[SK][0-9][0-9]}
+usr_params=$*
 # ... and compare them
 if [ $link == $base ] ; then
 	RUNMODE=manual
@@ -139,6 +140,12 @@ is_ref()
 
 start()
 {
+    lsmod | grep sx_core > /dev/null
+    is_core_running=$?
+    if [ $is_core_running -eq 0 ]; then
+        echo_warning $"sx_core service been already started"
+        return 0
+    fi
 	/sbin/modprobe 8021q
 	RC=$?
 	if [ $RC -ne 0 ]; then
@@ -158,28 +165,7 @@ start()
 		return $RC
 	fi
 
-	if [ "x$udevd_restart" != "xno" ]; then
-		if [ -x /sbin/udevtrigger ]; then
-			echo "Reloading udev:"
-			/sbin/udevtrigger
-			RC=$?
-			if [ $RC = 1 ]; then
-				echo "Failed to run udevtrigger."
-				return $RC
-			fi
-		fi
-		if [ -x /sbin/udevadm ]; then
-			echo "Reloading udev:"
-			/sbin/udevadm trigger
-			RC=$?
-			if [ $RC = 1 ]; then
-				echo "Failed to run udevadm."
-				return $RC
-			fi
-		fi
-	fi
-
-       /sbin/modprobe sx_netdev
+        /sbin/modprobe sx_netdev
         RC=$?
         if [ $RC -ne 0 ]; then
                 echo_failure $"Loading sx_netdev: "
@@ -199,7 +185,7 @@ start()
 
 	RC=$?
 	if [ $RC -ne 0 ]; then
-		echo_failure $"Preparing /dev/sxdevs/sxcdev device"
+		echo_failure $"Preparing /dev/sxdevs/sxcdev major='$major' device"
 		return $RC
 	fi
 
@@ -215,7 +201,7 @@ start()
 
     RC=$?
     if [ $RC -ne 0 ]; then
-        echo_failure $"Preparing /dev/sxdevs/bfdcdev device"
+        echo_failure $"Preparing /dev/sxdevs/bfdcdev major='$major' device"
         return $RC
     fi
 
@@ -376,7 +362,7 @@ status()
 RC=0
 start_time=$(date +%s | tr -d '[:space:]')
 
-trap_handler()
+default_trap_handler()
 {
 	let run_time=$(date +%s | tr -d '[:space:]')-${start_time}
 
@@ -389,7 +375,77 @@ trap_handler()
 	return 0
 }
 
-trap 'trap_handler' 2 9 15
+SCRIPTNAME=$(basename $0)
+LOCK_DIR="/var/lock/${SCRIPTNAME}"
+PIDFILE="${LOCK_DIR}/PID"
+
+lock()
+{
+  mkdir $LOCK_DIR 2> /dev/null
+  if [ $? == 0 ]; then
+     echo $$ > $PIDFILE
+     DO_UNLOCK=1
+     return 0
+  else
+    return 1
+  fi
+}
+
+remove_lock()
+{
+  rm -rf $LOCK_DIR
+}
+
+exit_on_signal()
+{
+  default_trap_handler
+  echo "Kill, cleanup..."
+  if [ "$DO_UNLOCK" != "0" ]; then
+     remove_lock
+  fi
+  exit 1
+}
+
+exit_on_end()
+{
+  if [ "$DO_UNLOCK" != "0" ]; then
+    remove_lock
+  fi
+  exit $1
+}
+
+lock_failed()
+{
+  # check for PID
+  PID=$(cat $PIDFILE)
+
+  # Maybe there was an error reading the PID file
+  if [ $? != 0 ]; then
+     echo "$PIDFILE read failed, $SCRIPTNAME is running (PID ${PID})" >&2
+     DO_UNLOCK=1
+     exit 1
+  fi
+
+  # Check if the PID is really existing
+  if ! kill -0 $PID &>/dev/null; then
+     echo "Removing stale lock of nonexistant PID ${PID}" >&2
+     remove_lock
+     echo "Restarting myself (${SCRIPTNAME})" >&2
+     # On Unix-like operating systems, exec is a builtin command of the Bash shell. 
+     # It allows you to execute a command that completely replaces the current process. 
+     # The current shell process is destroyed, and entirely replaced by the command you specify.
+     exec "$0" $usr_params
+  else
+     echo "Locking failed, another instance of $SCRIPTNAME is still running (PID ${PID})" >&2
+     DO_UNLOCK=0
+     exit 1
+  fi
+}
+trap exit_on_signal INT KILL TERM 
+trap 'exit_on_end $?' QUIT EXIT
+
+# Lock mechanism to insure sxdkernel run as singleton 
+lock || lock_failed
 
 case $ACTION in
 	start)
