4.5.3196 [sx_sdk_4_5_3000, 521fbf7b1709df42e2b43c1b22c0c67c0834d868]

diff --git a/sx_scripts/sxdkernel b/sx_scripts/sxdkernel
--- a/sx_scripts/sxdkernel
+++ b/sx_scripts/sxdkernel
@@ -19,6 +19,7 @@
 # Therefore determine the base, follow a runlevel link name ...
 base=${0##*/}
 link=${base#*[SK][0-9][0-9]}
+usr_params=$*
 # ... and compare them
 if [ $link == $base ] ; then
 	RUNMODE=manual
@@ -38,6 +39,16 @@ if [ -z $FAST_BOOT ]; then
     export FAST_BOOT=0
 fi
 
+# Predefined PCI devices environment variable format:
+# export PREDEFINED_DEV_PCI_BUS=<dev_id>@<bus_id>,<dev_id>@<bus_id> ...
+# EXAMPLE:
+#     export PREDEFINED_DEV_PCI_BUS=1@06:00.0,2@03:00.0
+if [ -z $PREDEFINED_DEV_PCI_BUS ]; then
+	export PREDEFINED_DEV_PCI_BUS_PARAM=""
+else
+	export PREDEFINED_DEV_PCI_BUS_PARAM="predefined_dev_pci_bus=${PREDEFINED_DEV_PCI_BUS}"
+fi
+
 if [ "x$RESUME_SDK" == "x1" ]; then
     FAST_BOOT=1
 fi
@@ -46,6 +57,9 @@ RESTART=0
 
 UNLOAD_MODULES=""
 STATUS_MODULES="sx_core sx_netdev 8021q"
+
+SXDKERNEL_PRESTART="sxdkernel-pre-start"
+SXDKERNEL_POSTSTOP="sxdkernel-post-stop"
 
 #########################################################################
 # Get a sane screen width
@@ -139,6 +153,18 @@ is_ref()
 
 start()
 {
+	if [ -x "$SXDKERNEL_PRESTART" ]; then
+		"$SXDKERNEL_PRESTART"
+	else
+		# default sdkernel pre-start procedure
+		lsmod | grep sx_core > /dev/null
+		is_core_running=$?
+		if [ $is_core_running -eq 0 ]; then
+			echo_warning $"sx_core service been already started"
+			return 0
+		fi
+	fi
+
 	/sbin/modprobe 8021q
 	RC=$?
 	if [ $RC -ne 0 ]; then
@@ -147,9 +173,9 @@ start()
 	fi
 
 	if [ -z $CHIP_TYPE ]; then
-		/sbin/modprobe sx_core cq_thread_sched_priority=98 g_chip_type=1 fast_boot=$FAST_BOOT reset_trigger=$RESET_TRIGGER
+		/sbin/modprobe sx_core cq_thread_sched_priority=98 g_chip_type=1 fast_boot=$FAST_BOOT reset_trigger=$RESET_TRIGGER $PREDEFINED_DEV_PCI_BUS_PARAM
 	else
-		/sbin/modprobe sx_core cq_thread_sched_priority=98 g_chip_type=$CHIP_TYPE fast_boot=$FAST_BOOT reset_trigger=$RESET_TRIGGER
+		/sbin/modprobe sx_core cq_thread_sched_priority=98 g_chip_type=$CHIP_TYPE fast_boot=$FAST_BOOT reset_trigger=$RESET_TRIGGER $PREDEFINED_DEV_PCI_BUS_PARAM
 	fi
 
 	RC=$?
@@ -158,28 +184,7 @@ start()
 		return $RC
 	fi
 
-	if [ "x$udevd_restart" != "xno" ]; then
-		if [ -x /sbin/udevtrigger ]; then
-			echo "Reloading udev:"
-			/sbin/udevtrigger
-			RC=$?
-			if [ $RC = 1 ]; then
-				echo "Failed to run udevtrigger."
-				return $RC
-			fi
-		fi
-		if [ -x /sbin/udevadm ]; then
-			echo "Reloading udev:"
-			/sbin/udevadm trigger
-			RC=$?
-			if [ $RC = 1 ]; then
-				echo "Failed to run udevadm."
-				return $RC
-			fi
-		fi
-	fi
-
-       /sbin/modprobe sx_netdev
+        /sbin/modprobe sx_netdev
         RC=$?
         if [ $RC -ne 0 ]; then
                 echo_failure $"Loading sx_netdev: "
@@ -199,7 +204,7 @@ start()
 
 	RC=$?
 	if [ $RC -ne 0 ]; then
-		echo_failure $"Preparing /dev/sxdevs/sxcdev device"
+		echo_failure $"Preparing /dev/sxdevs/sxcdev major='$major' device"
 		return $RC
 	fi
 
@@ -215,13 +220,25 @@ start()
 
     RC=$?
     if [ $RC -ne 0 ]; then
-        echo_failure $"Preparing /dev/sxdevs/bfdcdev device"
+        echo_failure $"Preparing /dev/sxdevs/bfdcdev major='$major' device"
         return $RC
     fi
 
-	echo_success $"Loading SX driver: "
+    echo_success $"Loading SX driver: "
 
-	return $RC
+    # check if we have sx_ib driver installed (on IB switch)
+    # if so, we'll load it.
+    /sbin/modinfo sx_ib > /dev/null 2>&1
+    RC=$?
+
+    if [ $RC -eq 0 ]; then
+        /sbin/modprobe sx_ib --force    # --force is a WA, to issues with BaseOS LK5.10 of unknown symbols
+        RC=$?
+    else
+        RC=0
+    fi
+
+    return $RC
 }
 
 rm_mod()
@@ -308,6 +325,14 @@ stop()
 
 	local done=0
 
+    # check if we have sx_ib up (on IB switch)
+    # if so, we'll unload it
+    if is_module sx_ib; then
+        is_ref sx_ib
+        unload sx_ib
+        done=1
+    fi
+
     # Unload sx_bfd
     if is_module sx_bfd; then
         is_ref sx_bfd
@@ -315,31 +340,34 @@ stop()
         done=1
     fi
 
-        # Unload mlx_sx_netdev
-	if is_module sx_netdev; then
-		is_ref sx_netdev
-		unload sx_netdev
-	fi
+	if [ -x "$SXDKERNEL_POSTSTOP" ]; then
+		"$SXDKERNEL_POSTSTOP"
+	else
+		# default sxdkernel post-stop procedure
+		# Unload mlx_sx_netdev
+		if is_module sx_netdev; then
+			is_ref sx_netdev
+			unload sx_netdev
+		fi
 
-	# Unload mlx_sx_core
-	if is_module sx_core; then
-		is_ref sx_core
-		unload sx_core
-		rm -rf /dev/sxdevs
-		done=1
-	fi
+		# Unload mlx_sx_core
+		if is_module sx_core; then
+			is_ref sx_core
+			unload sx_core
+			rm -rf /dev/sxdevs
+			done=1
+		fi
 
-	if is_module 8021q; then
-		is_ref 8021q
-		unload 8021q
-		done=1
+		if is_module 8021q; then
+			is_ref 8021q
+			unload 8021q
+			done=1
+		fi
 	fi
-
 
 	if [ $done -eq 1 ]; then
 		echo_success $"Unloading SX driver: "
 	fi
-	sleep 1
 }
 
 status()
@@ -376,7 +404,7 @@ status()
 RC=0
 start_time=$(date +%s | tr -d '[:space:]')
 
-trap_handler()
+default_trap_handler()
 {
 	let run_time=$(date +%s | tr -d '[:space:]')-${start_time}
 
@@ -389,7 +417,77 @@ trap_handler()
 	return 0
 }
 
-trap 'trap_handler' 2 9 15
+SCRIPTNAME=$(basename $0)
+LOCK_DIR="/var/lock/${SCRIPTNAME}"
+PIDFILE="${LOCK_DIR}/PID"
+
+lock()
+{
+  mkdir $LOCK_DIR 2> /dev/null
+  if [ $? == 0 ]; then
+     echo $$ > $PIDFILE
+     DO_UNLOCK=1
+     return 0
+  else
+    return 1
+  fi
+}
+
+remove_lock()
+{
+  rm -rf $LOCK_DIR
+}
+
+exit_on_signal()
+{
+  default_trap_handler
+  echo "Kill, cleanup..."
+  if [ "$DO_UNLOCK" != "0" ]; then
+     remove_lock
+  fi
+  exit 1
+}
+
+exit_on_end()
+{
+  if [ "$DO_UNLOCK" != "0" ]; then
+    remove_lock
+  fi
+  exit $1
+}
+
+lock_failed()
+{
+  # check for PID
+  PID=$(cat $PIDFILE)
+
+  # Maybe there was an error reading the PID file
+  if [ $? != 0 ]; then
+     echo "$PIDFILE read failed, $SCRIPTNAME is running (PID ${PID})" >&2
+     DO_UNLOCK=1
+     exit 1
+  fi
+
+  # Check if the PID is really existing
+  if ! kill -0 $PID &>/dev/null; then
+     echo "Removing stale lock of nonexistant PID ${PID}" >&2
+     remove_lock
+     echo "Restarting myself (${SCRIPTNAME})" >&2
+     # On Unix-like operating systems, exec is a builtin command of the Bash shell. 
+     # It allows you to execute a command that completely replaces the current process. 
+     # The current shell process is destroyed, and entirely replaced by the command you specify.
+     exec "$0" $usr_params
+  else
+     echo "Locking failed, another instance of $SCRIPTNAME is still running (PID ${PID})" >&2
+     DO_UNLOCK=0
+     exit 1
+  fi
+}
+trap exit_on_signal INT KILL TERM 
+trap 'exit_on_end $?' QUIT EXIT
+
+# Lock mechanism to insure sxdkernel run as singleton 
+lock || lock_failed
 
 case $ACTION in
 	start)
